config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :categories
  resources :articles do
    resources :votes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tags
	get '/signup', to: 'users#new'
  	resources :users

  	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_one_attached :header_image
  belongs_to :category
  has_many :votes, dependent: :destroy

  validates_presence_of :author, :text, :title, :category, :header_image

  scope :most_recent_by_category, lambda {
    from(
      <<~SQL
        (
          SELECT articles.*
          FROM articles JOIN (
             SELECT category_id, max(created_at) AS created_at
             FROM articles
             GROUP BY category_id
          ) latest_by_category
          ON articles.created_at = latest_by_category.created_at
          AND articles.category_id = latest_by_category.category_id
        ) articles
      SQL
    )
  }
  has_many :taggings
  has_many :tags, through: :taggings
  def tag_list
    tags.collect(&:name).join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :logged_in_user, only: %i[create destroy]

  # GET /articles
  # GET /articles.json
  def index
    cate = params[:cate]

    @articles = if !cate.nil?
                  Article.where(category_id: cate)
                else
                  Article.all.order('created_at DESC')
                end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    respond_to do |format|
      if @article.destroy
        format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @article }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @article = Article.find(params[:id])
    @article.upvote_from current_user
  end

  def downvote
    @article = Article.find(params[:id])
    @article.downvote_from current_user
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :text, :header_image, :category_id, :tag_list)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def like_dislike_btn
    pre_vote = @article.votes.find { |vote| vote.user_id == current_user.id }
    if pre_vote
      button_to 'Unlike', article_vote_path(@article, pre_vote), method: :delete, class: 'btn btn-secondary'
    else
      button_to 'Like', article_votes_path(@article), method: :post, class: 'btn btn-secondary'
    end
  end

  def edit_btn(_user)
    link_to 'Edit', edit_article_path(@article) if current_user?(@article.author)
  end

  def destroy_btn(_user)
    return unless current_user?(@article.author)

    link_to 'Delete', @article, method: :delete,
                                data: { confirm: 'You sure?' }
  end

  def recent_article
    articles = Category.includes(:most_recent_article).all
    articles
  end

  def vote_count
    @article.votes.count == 1 ? 'Like' : 'Likes'
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true,class: "login container") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= form.label :header_image %>
    <%= form.file_field :header_image, class: "form-control-file" ,required: true %>
  </div>
  
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control",required: true, 
                    minlength: 5,
                    maxlength: 100 %>
  </div>

  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_field :text, class: "form-control",required: true, 
                    minlength: 100,
                    maxlength: 800%>
  </div>

 <div class="form-group">
    <%= form.select :category_id, Category.all.map {|c| [c.name, c.id]}, class: "form-control" %>
  </div>
  <div>
    <p>
    <%= form.label :tag_list %><br />
    <%= form.text_field :tag_list , class: "form-control"%>
  </p>
</div class="form-group">
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class='container'>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="articles">
<% @articles.each do |article| %>
  <div class="card mb-0 border-0 h-100" style="width: 50%">
    
    <div class="arts">
      <div class="img_div">
        <%= image_tag article.header_image, class: 'card-img'%>
      </div>
      <div class="art-body" >
        <div class="card-body">     
          <h5 class="card-title font-weight-bold"><%= article.category.name %></h5>
          <h4 class='card-text font-weight-bold'><%= article.title %></h4>
          <p class="card-text text-truncate"><%= article.text %></p>
          <p class="card-text text-truncate">By <%= article.author.name %></p>
          <div class="mut">
            <p class="card-text"><small class="text-muted"><%= link_to 'Read more', article_path(article), class: 'readmore' %></small></p>
            <span class= "votes"><%= pluralize(article.votes.count, 'Vote') %></span>
          </div>
        </div>
      </div>
    </div>
    
  </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1 class='container'>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class= 'article'>
	<h1 class="title"><%= @article.title%></h1>
  	<p> By <%= @article.author.name %></p>
	<div class= 'img-article'>
	  <%= image_tag @article.header_image, class: 'style_image'%>
	</div>

	<div class="container-text container">
		<%= markdown(@article.text)%>
	</div>
	<div class="likes">
		<p><%= @article.votes.count %> <%= vote_count %></p>
		<% if logged_in? %>
			<%= like_dislike_btn %>
		<% end %>
	</div>
	<div>
		<p>
		  Tags:
		  <% @article.tags.each do |tag| %>
		    <%= link_to tag.name, tag_path(tag) %>
		  <% end %>
		</p>
	</div>
	<div class="nav-links">
		<span><%= edit_btn(current_user)%><span>
		<span><%= destroy_btn(current_user)%></span>
	</div>

</div>
 