config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :categories
  resources :articles do
    resources :votes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tags
	get '/signup', to: 'users#new'
  	resources :users

  	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  has_one :most_recent_article, lambda {
    merge(Article.most_recent_by_category)
  }, class_name: 'Article', inverse_of: :category

  validates_presence_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :admin_user, only: %i[create new]
  before_action :logged_in_user, only: [:show]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order('created_at DESC')
  end

  # GET /categories/1
  # GET /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    respond_to do |format|
      if @category.destroy
        format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @category }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true,class: "login container" ) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name,class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class='container'>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="card bg-dark text-white cat">
  <% popular = Vote.popular %>
  <% popular.each do |vote| %>
  <%= image_tag vote.article.header_image, class: "card-img art-1 " %>
  <div class="card-img-overlay texts">
    <h5 class="card-title font-weight-bold "><%= vote.article.title %></h5>
    <p class="card-text text-truncate"><%= vote.article.text %></p>
    <p class="card-text "><small class="text-muted"><%= link_to 'Read more', article_path(vote.article), class: 'readmore' %></small></p>
  </div>
  <% end %>
</div>
<div class="categories">
  
  <% recent_article.each do |article| %>
  <div class="card bg-dark border-0" text-white style="width: 16.66%;">
  <% if article.most_recent_article&.header_image %>
        <%= image_tag article.most_recent_article&.header_image, class: "card-img" %>
     <% end %>

  <div class="card-img-overlay border-0 catext">
    <h5 class="card-title"><%= article.name %></h5>

    <p class="card-text font-weight-bold"><%= article.most_recent_article.present? ? article.most_recent_article&.title : '' %></p>
  </div>

</div>
<% end %>
</div>

app/views/categories/new.html.erb
<h1 class='container'>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>