config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :categories
  resources :articles do
    resources :votes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tags
	get '/signup', to: 'users#new'
  	resources :users

  	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div>
    <a class="logo"href="#">Sporf</a>
  </div>
  <div class="first">
    <ul>
      <li><a href="#">Privacy Policy</a></li>
      <li><a href="#">Terms & Conditions</a></li>
      <li class='copy'>Copyright 2014. All rights reserved</li>
    </ul>
  </div>
  <div class="second">
    <ul>
      <li>Connect with us: </li>
      <li><a href="#"><i class="fa fa-facebook"></i></a></li>
      <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
      <li><a href="#"><i class="fa fa-instagram"></i></a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar mb-2">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'SPORF', root_path , class: "lnk"%>
    </div>
     <% Category.all.each do |category|%>
      <ul class="cats">
          <li><%= link_to category.name, articles_path(:cate => category.id), class: 'links' %></li>
      </ul>
    <% end %>
    <% if logged_in? %>
      <ul class="nav navbar-right ">
        <li class="lnk"> <%= admin_btn(current_user) %></li>
        <li><%= link_to 'New Article', new_article_path, class: "lnk" %></li>
        <li><%= link_to "Log out", logout_path, class: "lnk", method: :delete %></li> 
      </ul>
    <% else %>
      <ul class="nav navbar-right ">
        <li><%= link_to "Log in", login_path, class: "lnk" %></li> 
        <li><%= link_to "Sign up", signup_path, class: "lnk" %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sporf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='contai'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
  <script>
  $(document).on('ready page:load', function () {
    $('#post_tag_ids').chosen({
      allow_single_deselect: true,
      width: '100%'
    })
  });
</script>
</html>